### ISSUE TITLE
Deletion request of alexinite/fusion

### ISSUE THREAD

**Issue by alexasterisk** [UpliftGames/wally-index#23]
I would like to request the deletion of [alexinite/fusion](https://github.com/UpliftGames/wally-index/blob/main/alexinite/fusion) which is a package uploaded by me. I am requesting deletion of this as @Elttob has uploaded the Fusion package themselves and it no longer serves a purpose of being on the registry.

**Comment by magnalite** [comment]
Our policy is to never delete packages unless we absolutely have to. In the future you will be able to yank packages to prevent people discovering them. See: https://github.com/UpliftGames/wally/issues/3

**Comment by alexasterisk** [comment]
I understand that now, and thinking of this, what if there was a system in place like NPM's [deprecated] tag? So users could mark their project deprecated with a message following it (i.e. why? or what to use instead)

**Comment by magnalite** [comment]
This is the behaviour that yanking achieves. It "deletes" the package in the sense that people won't be able to discover it or depend upon it if they don't already. However if they are depending on it already it'll still exist in the registry and not break their builds/workflow by suddenly vanishing. It'll also notify them that they should stop using that package.
