### ISSUE TITLE
Unable to publish package

### ISSUE THREAD

**Issue by CompeyDev** [UpliftGames/wally-index#9]
The documentation on the wally README does not exactly clarify as to publish a package in detail. How would I go about publishing a scoped package? I seem to be getting a "no permissions" error. Thanks in advance :)

![image](https://user-images.githubusercontent.com/74418041/197375749-f05d1991-4a24-47da-8e6f-220015e49453.png)

**Comment by Kampfkarren** [comment]
You have to publish it as your own username, or talk to Wally staff to setup a scope for your org.

**Comment by CompeyDev** [comment]
Oh, is there a Wally community or such where I can get Wally staff to setup a scope for the org?

**Comment by CompeyDev** [comment]
Created #10 regarding this.
